# Generated by Django 5.1.2 on 2024-10-25 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_marca_product_marca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='marca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.marca'),
        ),
    ]
