# Generated by Django 5.1.2 on 2024-11-19 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='emisao_som',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
