# Generated by Django 5.1.2 on 2024-11-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_product_ean_product_reference_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='more_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
