# Generated by Django 5.1.2 on 2024-11-20 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0006_order_final_total_order_shipping_cost_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='final_total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_cost',
        ),
        migrations.RemoveField(
            model_name='order',
            name='shipping_method',
        ),
    ]
